### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(QtDSLogin)
add_subdirectory(QtDSLoginContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    QtDSLoginplugin
    QtDSLoginContentplugin
    QtQuickDesignerComponents)